### ISSUE TITLE
Can't compile for PHP 7.4

### ISSUE THREAD

**Issue by anxgstadler** [php-opencv/php-opencv#18]
After 100% of "building", many screens of "installing" and some lines of "checking", the process ends with this error message:

```
/php-opencv/source/opencv2/core/opencv_mat.cc: In function 'void opencv_mat_init()':
/php-opencv/source/opencv2/core/opencv_mat.cc:858:49: error: invalid conversion from 'void (*)(zval*, zval*, zval*, void**)' {aka 'void (*)(_zval_struct*, _zval_struct*, _zval_struct*, void**)'} to 'zend_object_write_property_t' {aka '_zval_struct* (*)(_zval_struct*, _zval_struct*, _zval_struct*, void**)'} [-fpermissive]
     opencv_mat_object_handlers.write_property = opencv_mat_write_property;
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:194: source/opencv2/core/opencv_mat.lo] Error 1
```

Some more infos:
```
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
```

**Comment by morozovsk** [comment]
https://github.com/php-opencv/php-opencv#requirements
>PHP 7.0 / 7.1 / 7.2

**Comment by anxgstadler** [comment]
Yes, I saw that.

I guess the main question is: Are there any plans to update this project to work with PHP 7.4?
As version 7.2 is going to reach its official end of life in only 6 days on November 30th (https://www.php.net/supported-versions.php), it would be irresponsible for me to set up a 7.2 system in a production environment just in order to run OpenCV...

**Comment by morozovsk** [comment]
https://github.com/php-opencv/php-opencv/issues/19

**Comment by morozovsk** [comment]
now php-opencv supports php 7.4 / 8.0
